### ISSUE TITLE
This plugin doesn't work for ditamap file

### ISSUE THREAD

**Issue by yeastarcarol** [oxygenxml/dita-embed-html-xslfo#1]
Hi, I tested the plugin.
It worked for dita file, but didn't work for a ditamap file, when I added embedded html in the element   <shortdesc> there is no error in oxygen editor. But the webhelp output doesn't show the embedded html.

**Comment by raducoravu** [comment]
Yes, this plugin only works for embedding HTML content in a DITA topic.
For WebHelp output maybe one of the configuration parameters will help:

https://www.oxygenxml.com/doc/versions/20.0/ug-editor/topics/webhelp-responsive-plugin-additional-parameters.html

If not, you can drop an email to "support@oxygenxml.com", tell us what version of Oxygen you are using, give us more details about your use case, maybe attach a screenshot showing in which part of the output you want to have the custom HTML content...
